---
- name: ping all pxe node to checking all node is ok
  ping:
  tags: add

- name: copy script set_pxe_static.sh to /tmp
  copy: src=/root/tools/set_pxe_static.sh dest=/tmp/
  run_once: False
  tags: add
- name: set pxe network to static include gateway
  shell: bash /tmp/set_pxe_static.sh {{pxe_net_card_name}} {{pxe_gateway}}
  run_once: False
  tags: add

- name: copy script add_vlan_interface.sh to /tmp
  copy: src=/root/tools/add_vlan_interface.sh dest=/tmp/
  run_once: False
  tags: add

- name: add vlan network for admin
  shell: bash /tmp/add_vlan_interface.sh {{pxe_net_card_name}} {{admin_vlan_card_name}} {{admin_vlanid}} {{admin_ip_segment}} {{admin_gateway}}
  run_once: False
  when: pxe_net_card_name != admin_vlan_card_name and admin_vlanid|int != 0
  tags: add

- name: set interworking vlan network for platform vm
  script: /root/tools/set_interworking_vlan_interface.sh {{tm_vlan_card_name}}
  run_once: False
  tags: add

- name: add vlan network for external
  shell: bash /tmp/add_vlan_interface.sh {{pxe_net_card_name}} {{external_vlan_card_name}} {{external_vlanid}} {{external_ip_segment}}
  when: external_vlanid|int != 0
  run_once: False
  tags: add
  
- name: add vlan network for storage
  shell: bash /tmp/add_vlan_interface.sh {{pxe_net_card_name}} {{storage_vlan_card_name}} {{storage_vlanid}} {{storage_ip_segment}}
  when: storage_vlanid|int != 0
  run_once: False
  tags: add

- name: add tunnel network for vm to vm (vxlan)
  shell: bash /tmp/add_vlan_interface.sh {{pxe_net_card_name}} {{tunnel_vlan_card_name}} {{tunnel_vlanid}} {{tunnel_ip_segment}}
  when: tunnel_vlanid != admin_vlanid and tunnel_vlanid|int != 0
  run_once: False
  tags: add

- name: add internal vip interface for https
  shell: bash /tmp/add_vlan_interface.sh {{pxe_net_card_name}} {{internal_vip_vlan_card_name}} {{internal_vip_vlanid}} {{internal_vip_ip_segment}}
  when: https == "yes" and internal_vlanid|int != 0
  run_once: False
  tags: add

- name: restart network
  shell: service network restart
  tags: add

