---
#The pxe is not multiplexed into the management network, and the management network is multiplexed into the service network.
- name: get the network connection ip 1
  shell: |
    ping -c 2 "{{hostvars[item[0]]['ansible_' + item[1]].ipv4.address }}"
  when: pxe_net_card_name != admin_vlan_card_name and admin_vlan_card_name == tunnel_vlan_card_name
  register: netinfo
  ignore_errors: yes
  with_nested:
    - "{{ groups['all'] }}"
    - ["{{admin_vlan_card_name}}.{{admin_vlanid}}", "{{external_vlan_card_name}}.{{external_vlanid}}", "{{storage_vlan_card_name}}.{{storage_vlanid}}"]

#Pxe is not multiplexed into the management network. The management network is not multiplexed into the service network.  
- name: get the network connection ip 2
  shell: |
    ping -c 2 "{{hostvars[item[0]]['ansible_' + item[1]].ipv4.address }}"
  when: pxe_net_card_name != admin_vlan_card_name and admin_vlan_card_name != tunnel_vlan_card_name
  register: netinfo
  ignore_errors: yes
  with_nested:
    - "{{ groups['all'] }}"
    - ["{{admin_vlan_card_name}}.{{admin_vlanid}}","{{tunnel_vlan_card_name}}.{{tunnel_vlanid}}", "{{external_vlan_card_name}}.{{external_vlanid}}", "{{storage_vlan_card_name}}.{{storage_vlanid}}"]

- name: get the network connection ip 3
  shell: |
    ping -c 2 "{{hostvars[item[0]]['ansible_' + item[1]].ipv4.address }}"
  when: pxe_net_card_name == admin_vlan_card_name 
  register: netinfo
  ignore_errors: yes
  with_nested:
    - "{{ groups['all'] }}"
    - ["{{tunnel_vlan_card_name}}.{{tunnel_vlanid}}", "{{external_vlan_card_name}}.{{external_vlanid}}", "{{storage_vlan_card_name}}.{{storage_vlanid}}"]
  
#- name: debug
#  debug: var=netinfo

- name: echo the no ping ip
  shell: echo "ip {{item.cmd}} is no ok" >> /tmp/noping.txt
  with_items:
   - "{{ netinfo.results }}"
  when: item.rc != 0
  delegate_to: localhost  

