---
#only for deploy node exec
#
- name: sync file
  hosts: all
  roles:
    - sync_file
- name: prepare deploy
  hosts: deploy
  roles:
    - set_hosts
    - ceph
    - swift
    - neutron

- name: prepare openstack settings
  hosts: deploy
  roles:
    - set_kolla_settings
